name: 02 - Workflow Events

on:
  push:
  workflow_dispatch:
  pull_request:
  # schedule:
  #    - cron: "*/10 * * * *"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Workflow was triggered by ${{ github.event_name }}"
    
