name: 05 - 1 - Event Filters and Activity types

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main

jobs:
    echo:
        steps:
            - name: Print message on screen
              runs-on: ubuntu_latest
              run: echo "Running wnenever a PR is opened or synchronized AND base branch is main"


