name: 05 - 2 - Event filters ad Activity types

on:
    pull_request:
        types: closed
        branches: main

jobs:
    echo:
        runs-on: ubuntu_latest
        steps:
            name: Echo the message on PR close
            run: echo "Running whenever a PR is closed"