name: 12 - Working with outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                description: Status of build
                type: choice
                options:
                    - success
                    - failure
                default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            name: ${{ steps.build.outputs.status }}
        steps:
            - name: print GITHUB_OUTPUT path
              run: echo $GITHUB_OUTPUT
            
            - name: Build
              id: build
              run: |
                echo "status=${{inputs.build-status}}" >> $GITHUB_OUTPUT
                
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: deploy
              if: ${{ needs.build.outputs.name }} == success
              run: echo "Deploying"


