name: Using Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Whether to execute cache step
                type: boolean
                default: true

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
             working-directory: 13-caching/react-app
        steps:
            # 1. Checkout the code
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            # 2. Install dependencies
            - name: Install dependencies
              run: npm ci
            # 3. unit testing , building
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"
        
        
        # 3. unit testing , building
        # 4. Deploy to a nonprod environment
                