name: 15 - Working with matrices

on:
  workflow_dispatch:

jobs:
  backward-compatibility:
    name: ${{ matrix.os }}-${{matrix.node}}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: 
         - ubuntu-latest
         - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup node
        
          
